spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edumaster_user
    username: {USERNAME}
    password: {USER_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: {MAIL_NAME}
    password: {MAIL_PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082
