spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edumaster_user
    username: root
    password: Ranchi#993116

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: rajat71203@gmail.com
    password: cowr jjrk fjoi iwgb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082
