spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edumaster_courses
    username: {USERNAME}
    password: {USER_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8081